#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Initialise with potentialFoam solution
runApplication potentialFoam

rm -f 0/phi

runApplication decomposePar

# Run the solver
runParallel foamRun

runApplication reconstructPar

# Run post-processing
runApplication particleTracks

#------------------------------------------------------------------------------
